spring:
    application:
        name: doctor-service
    jpa:
        hibernate:
            ddl-auto: update
        properties:
          hibernate:
            dialect: org.hibernate.dialect.PostgreSQLDialect
            format_sql: true
          show-sql: true
    datasource:
        url: jdbc:postgresql://localhost:5432/doctor_db
        username: postgres
        password: postgres
        driver-class-name: org.postgresql.Driver


server:
    port: 8082

eureka:
    client:
        enabled: false
